"""Device Type Resolvers used via regex to determine whether a binary sensor is a window or a door."""
# Device Translations
LANG_DOOR = [
    ("afrikaans", "deur"),
    ("albanian", "përmes"),
    ("amharic", "በኩል"),
    ("arabic", "بواسطة"),
    ("armenian", "միջոցով"),
    ("azerbaijani", "vasitəsilə"),
    ("basque", "bidez"),
    ("belarusian", "наскрозь"),
    ("bengali", "মাধ্যম"),
    ("bosnian", "kroz"),
    ("bulgarian", "през"),
    ("catalan", "per"),
    ("cebuano", "pinaagi sa"),
    ("chinese (simplified)", "通过"),
    ("chinese (traditional)", "通過"),
    ("corsican", "attraversu"),
    ("croatian", "kroz"),
    ("czech", "přes"),
    ("danish", "igennem"),
    ("dutch", "door"),
    ("esperanto", "tra"),
    ("estonian", "läbi"),
    ("finnish", "kautta"),
    ("french", "à travers"),
    ("frisian", "troch"),
    ("galician", "a través"),
    ("georgian", "მეშვეობით"),
    ("german", "durch"),
    ("greek", "διά μέσου"),
    ("gujarati", "દ્વારા"),
    ("haitian creole", "nan"),
    ("hausa", "ta hanyar"),
    ("hawaiian", "ma o"),
    ("hebrew", "דלת"),
    ("hindi", "के माध्यम से"),
    ("hmong", "txog"),
    ("hungarian", "keresztül"),
    ("icelandic", "í gegnum"),
    ("igbo", "site na"),
    ("indonesian", "melalui"),
    ("irish", "tríd"),
    ("italian", "attraverso"),
    ("japanese", "使って"),
    ("javanese", "liwat"),
    ("kannada", "ಮೂಲಕ"),
    ("kazakh", "арқылы"),
    ("khmer", "ឆ្លងកាត់"),
    ("korean", "...을 통하여"),
    ("kurdish", "bi rêve"),
    ("kyrgyz", "аркылуу"),
    ("lao", "ຜ່ານ"),
    ("latin", "propter"),
    ("latvian", "cauri"),
    ("lithuanian", "per"),
    ("luxembourgish", "duerch"),
    ("macedonian", "преку"),
    ("malagasy", "ny alalan '"),
    ("malay", "melalui"),
    ("malayalam", "വഴി"),
    ("maltese", "permezz"),
    ("maori", "na roto i"),
    ("marathi", "माध्यमातून"),
    ("mongolian", "гэхэд"),
    ("myanmar (burmese)", "မှတဆင့်"),
    ("nepali", "मार्फत"),
    ("norwegian", "gjennom"),
    ("nyanja (chichewa)", "kupyola"),
    ("pashto", "له لارې"),
    ("persian", "از طریق"),
    ("polish", "przez"),
    ("portuguese (portugal, brazil)", "por"),
    ("punjabi", "ਦੁਆਰਾ"),
    ("romanian", "prin"),
    ("russian", "от"),
    ("samoan", "ala atu"),
    ("scots gaelic", "troimhe"),
    ("serbian", "кроз"),
    ("sesotho", "ka ho"),
    ("shona", "kuburikidza"),
    ("sindhi", "جي ذريعي"),
    ("sinhala (sinhalese)", "ඔස්සේ"),
    ("slovak", "cez"),
    ("slovenian", "skozi"),
    ("somali", "iyada oo loo marayo"),
    ("spanish", "por"),
    ("sundanese", "ngaliwatan"),
    ("swahili", "kupitia"),
    ("swedish", "genom"),
    ("tagalog (filipino)", "sa pamamagitan ng"),
    ("tajik", "тавассути"),
    ("tamil", "மூலம்"),
    ("telugu", "ద్వారా"),
    ("thai", "ผ่าน"),
    ("turkish", "vasıtasıyla"),
    ("ukrainian", "через"),
    ("urdu", "کے ذریعے"),
    ("uzbek", "orqali"),
    ("vietnamese", "xuyên qua"),
    ("welsh", "trwodd"),
    ("xhosa", "ukugqitha"),
    ("yiddish", "דורך"),
    ("yoruba", "nipasẹ"),
    ("zulu", "ngokusebenzisa"),
    ("english", "door"),
]  # codespell: ignore

LANG_WINDOW = [
    ("afrikaans", "venster"),
    ("albanian", "dritare"),
    ("amharic", "መስኮት"),
    ("arabic", "نافذة او شباك"),
    ("armenian", "պատուհան"),
    ("azerbaijani", "pəncərə"),
    ("basque", "leihoa"),
    ("belarusian", "акно"),
    ("bengali", "জানলা"),
    ("bosnian", "prozor"),
    ("bulgarian", "прозорец"),
    ("catalan", "finestra"),
    ("cebuano", "bintana"),
    ("chinese (simplified)", "窗口"),
    ("chinese (traditional)", "窗口"),
    ("corsican", "finestra"),
    ("croatian", "prozor"),
    ("czech", "okno"),
    ("danish", "vindue"),
    ("dutch", "venster"),
    ("esperanto", "fenestro"),
    ("estonian", "aken"),
    ("finnish", "ikkuna"),
    ("french", "la fenêtre"),
    ("frisian", "finster"),
    ("galician", "xanela"),
    ("georgian", "ფანჯარა"),
    ("german", "Fenster"),
    ("greek", "παράθυρο"),
    ("gujarati", "વિંડો"),
    ("haitian creole", "fenèt"),
    ("hausa", "taga"),
    ("hawaiian", "pukaaniani"),
    ("hebrew", "חלון"),
    ("hindi", "खिड़की"),
    ("hmong", "qhov rais"),
    ("hungarian", "ablak"),
    ("icelandic", "glugga"),
    ("igbo", "windo"),
    ("indonesian", "jendela"),
    ("irish", "fuinneog"),
    ("italian", "finestra"),
    ("japanese", "窓"),
    ("javanese", "jendhela"),
    ("kannada", "ಕಿಟಕಿ"),
    ("kazakh", "терезе"),
    ("khmer", "បង្អួច"),
    ("korean", "창문"),
    ("kurdish", "pace"),
    ("kyrgyz", "терезе"),
    ("lao", "ປ່ອງຢ້ຽມ"),
    ("latin", "fenestram"),
    ("latvian", "logs"),
    ("lithuanian", "langas"),
    ("luxembourgish", "Fënster"),
    ("macedonian", "прозорец"),
    ("malagasy", "varavarankely"),
    ("malay", "tingkap"),
    ("malayalam", "ജാലകം"),
    ("maltese", "tieqa"),
    ("maori", "matapihi"),
    ("marathi", "विंडो"),
    ("mongolian", "цонх"),
    ("myanmar (burmese)", "ပြတင်းပေါက်"),
    ("nepali", "विन्डो"),
    ("norwegian", "vindu"),
    ("nyanja (chichewa)", "zenera"),
    ("pashto", "کړکۍ"),
    ("persian", "پنجره"),
    ("polish", "okno"),
    ("portuguese (portugal, brazil)", "janela"),
    ("punjabi", "ਵਿੰਡੋ"),
    ("romanian", "fereastră"),
    ("russian", "окно"),
    ("samoan", "faʻamalama"),
    ("scots gaelic", "uinneag"),
    ("serbian", "прозор"),
    ("sesotho", "fensetere"),
    ("shona", "hwindo"),
    ("sindhi", "دري"),
    ("sinhala (sinhalese)", "කවුළුව"),
    ("slovak", "okno"),
    ("slovenian", "okno"),
    ("somali", "daaqad"),
    ("spanish", "ventana"),
    ("sundanese", "jandela"),
    ("swahili", "dirisha"),
    ("swedish", "fönster"),
    ("tagalog (filipino)", "bintana"),
    ("tajik", "тиреза"),
    ("tamil", "ஜன்னல்"),
    ("telugu", "కిటికీ"),
    ("thai", "หน้าต่าง"),
    ("turkish", "pencere"),
    ("ukrainian", "вікно"),
    ("urdu", "ونڈو"),
    ("uzbek", "oyna"),
    ("vietnamese", "cửa sổ"),
    ("welsh", "ffenestr"),
    ("xhosa", "iwindow"),
    ("yiddish", "פענצטער"),
    ("yoruba", "ferese"),
    ("zulu", "iwindi"),
    ("english", "window"),
]  # codespell: ignore
