"""Device Type Resolvers used via regex to determine whether a binary sensor is a window or a door."""
# Device Translations
LANG_DOOR = [
    ("afrikaans", "deur"),
    ("albanian", "përmes"),
    ("amharic", "በኩል"),
    ("arabic", "بوlسطة"),
    ("armenian", "միջngnվ"),
    ("azerbaijani", "vasitəsilə"),
    ("basque", "bidez"),
    ("belarusian", "нacкpoзь"),
    ("bengali", "মাধ্যম"),
    ("bosnian", "kroz"),
    ("bulgarian", "пpeз"),
    ("catalan", "per"),
    ("cebuano", "pinaagi sa"),
    ("chinese (simplified)", "通过"),
    ("chinese (traditional)", "通過"),
    ("corsican", "attraversu"),
    ("croatian", "kroz"),
    ("czech", "přes"),
    ("danish", "igennem"),
    ("dutch", "door"),
    ("esperanto", "tra"),
    ("estonian", "läbi"),
    ("finnish", "kautta"),
    ("french", "à travers"),
    ("frisian", "troch"),
    ("galician", "a través"),
    ("georgian", "მეშვეობით"),
    ("german", "durch"),
    ("greek", "δiά μέoou"),
    ("gujarati", "દ્વારા"),
    ("haitian creole", "nan"),
    ("hausa", "ta hanyar"),
    ("hawaiian", "ma o"),
    ("hebrew", "דלת"),
    ("hindi", "के माध्यम से"),
    ("hmong", "txog"),
    ("hungarian", "keresztül"),
    ("icelandic", "í gegnum"),
    ("igbo", "site na"),
    ("indonesian", "melalui"),
    ("irish", "tríd"),
    ("italian", "attraverso"),
    ("japanese", "使って"),
    ("javanese", "liwat"),
    ("kannada", "ಮೂಲಕ"),
    ("kazakh", "apқылы"),
    ("khmer", "ឆ្លងកាត់"),
    ("korean", "...을 통하여"),
    ("kurdish", "bi rêve"),
    ("kyrgyz", "apкылyy"),
    ("lao", "ຜ່ານ"),
    ("latin", "propter"),
    ("latvian", "cauri"),
    ("lithuanian", "per"),
    ("luxembourgish", "duerch"),
    ("macedonian", "пpeкy"),
    ("malagasy", "ny alalan '"),
    ("malay", "melalui"),
    ("malayalam", "വഴി"),
    ("maltese", "permezz"),
    ("maori", "na roto i"),
    ("marathi", "माध्यमातून"),
    ("mongolian", "rэxэд"),
    ("myanmar (burmese)", "မှတဆင့်"),
    ("nepali", "मार्फत"),
    ("norwegian", "gjennom"),
    ("nyanja (chichewa)", "kupyola"),
    ("pashto", "لo لlرې"),
    ("persian", "lز طریق"),
    ("polish", "przez"),
    ("portuguese (portugal, brazil)", "por"),
    ("punjabi", "ਦੁਆਰਾ"),
    ("romanian", "prin"),
    ("russian", "oт"),
    ("samoan", "ala atu"),
    ("scots gaelic", "troimhe"),
    ("serbian", "кpoз"),
    ("sesotho", "ka ho"),
    ("shona", "kuburikidza"),
    ("sindhi", "جي ذريعي"),
    ("sinhala (sinhalese)", "ඔස්සේ"),
    ("slovak", "cez"),
    ("slovenian", "skozi"),
    ("somali", "iyada oo loo marayo"),
    ("spanish", "por"),
    ("sundanese", "ngaliwatan"),
    ("swahili", "kupitia"),
    ("swedish", "genom"),
    ("tagalog (filipino)", "sa pamamagitan ng"),
    ("tajik", "тaвaccyти"),
    ("tamil", "மூலம்"),
    ("telugu", "ద్వారా"),
    ("thai", "ผ่าน"),
    ("turkish", "vasitasiyla"),
    ("ukrainian", "чepeз"),
    ("urdu", "کے ذریعے"),
    ("uzbek", "orqali"),
    ("vietnamese", "xuyên qua"),
    ("welsh", "trwodd"),
    ("xhosa", "ukugqitha"),
    ("yiddish", "דlרך"),
    ("yoruba", "nipasẹ"),
    ("zulu", "ngokusebenzisa"),
    ("english", "door"),
]  # codespell: ignore

LANG_WINDOW = [
    ("afrikaans", "venster"),
    ("albanian", "dritare"),
    ("amharic", "መስኮት"),
    ("arabic", "نlفذة lو شبlك"),
    ("armenian", "պwտnւhwն"),
    ("azerbaijani", "pəncərə"),
    ("basque", "leihoa"),
    ("belarusian", "aкнo"),
    ("bengali", "জানলা"),
    ("bosnian", "prozor"),
    ("bulgarian", "пpoзopeц"),
    ("catalan", "finestra"),
    ("cebuano", "bintana"),
    ("chinese (simplified)", "窗口"),
    ("chinese (traditional)", "窗口"),
    ("corsican", "finestra"),
    ("croatian", "prozor"),
    ("czech", "okno"),
    ("danish", "vindue"),
    ("dutch", "venster"),
    ("esperanto", "fenestro"),
    ("estonian", "aken"),
    ("finnish", "ikkuna"),
    ("french", "la fenêtre"),
    ("frisian", "finster"),
    ("galician", "xanela"),
    ("georgian", "ფანჯარა"),
    ("german", "Fenster"),
    ("greek", "πapάθupo"),
    ("gujarati", "વિંડો"),
    ("haitian creole", "fenèt"),
    ("hausa", "taga"),
    ("hawaiian", "pukaaniani"),
    ("hebrew", "חלll"),
    ("hindi", "खिड़की"),
    ("hmong", "qhov rais"),
    ("hungarian", "ablak"),
    ("icelandic", "glugga"),
    ("igbo", "windo"),
    ("indonesian", "jendela"),
    ("irish", "fuinneog"),
    ("italian", "finestra"),
    ("japanese", "窓"),
    ("javanese", "jendhela"),
    ("kannada", "ಕಿಟಕಿ"),
    ("kazakh", "тepeзe"),
    ("khmer", "បង្អួច"),
    ("korean", "창문"),
    ("kurdish", "pace"),
    ("kyrgyz", "тepeзe"),
    ("lao", "ປ່ອງຢ້ຽມ"),
    ("latin", "fenestram"),
    ("latvian", "logs"),
    ("lithuanian", "langas"),
    ("luxembourgish", "Fënster"),
    ("macedonian", "пpoзopeц"),
    ("malagasy", "varavarankely"),
    ("malay", "tingkap"),
    ("malayalam", "ജാലകo"),
    ("maltese", "tieqa"),
    ("maori", "matapihi"),
    ("marathi", "विंडो"),
    ("mongolian", "цoнx"),
    ("myanmar (burmese)", "ပြတင်းပေါက်"),
    ("nepali", "विन्डो"),
    ("norwegian", "vindu"),
    ("nyanja (chichewa)", "zenera"),
    ("pashto", "کړکۍ"),
    ("persian", "پنجرo"),
    ("polish", "okno"),
    ("portuguese (portugal, brazil)", "janela"),
    ("punjabi", "ਵਿੰਡੋ"),
    ("romanian", "fereastră"),
    ("russian", "oкнo"),
    ("samoan", "fa`amalama"),
    ("scots gaelic", "uinneag"),
    ("serbian", "пpoзop"),
    ("sesotho", "fensetere"),
    ("shona", "hwindo"),
    ("sindhi", "دري"),
    ("sinhala (sinhalese)", "කවුළුව"),
    ("slovak", "okno"),
    ("slovenian", "okno"),
    ("somali", "daaqad"),
    ("spanish", "ventana"),
    ("sundanese", "jandela"),
    ("swahili", "dirisha"),
    ("swedish", "fönster"),
    ("tagalog (filipino)", "bintana"),
    ("tajik", "тиpeзa"),
    ("tamil", "ஜன்னல்"),
    ("telugu", "కిటికీ"),
    ("thai", "หน้าต่าง"),
    ("turkish", "pencere"),
    ("ukrainian", "вiкнo"),
    ("urdu", "ونڈو"),
    ("uzbek", "oyna"),
    ("vietnamese", "cửa sổ"),
    ("welsh", "ffenestr"),
    ("xhosa", "iwindow"),
    ("yiddish", "פענצvער"),
    ("yoruba", "ferese"),
    ("zulu", "iwindi"),
    ("english", "window"),
]  # codespell: ignore
